import Head from "next/head";
import {Inter} from "@next/font/google";

import Clients from "@/components/clients";
import Projects from "@/components/projects";
import {Divider} from "antd";

const inter = Inter({subsets: ["latin"]});

export default function Home({clients}: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-screen h-screen px-12">
        <h1 className="text-2xl text-center">Management APP Hello</h1>
        <Projects />
        <Divider />
        <Clients />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  // for build time only fetch - getStaticProps
  // const {data} = await client.query({
  //   query: GET_CLIENTS,
  // });

  return {
    props: {},
  };
}
